from django.core.management import BaseCommand

from sacco.models import Customer


class Command(BaseCommand):
    def handle(self, *args, **options):
        customers = [{"first_name":"Sholom","last_name":"Jessett","email":"sjessett0@dyndns.org","gender":"Male","weight":52,"dob":"2000-10-12"},
{"first_name":"Jefferey","last_name":"Eltun","email":"jeltun1@engadget.com","gender":"Male","weight":64,"dob":"2005-06-04"},
{"first_name":"Merilee","last_name":"Endicott","email":"mendicott2@boston.com","gender":"Female","weight":100,"dob":"2002-12-02"},
{"first_name":"Rorke","last_name":"Coxon","email":"rcoxon3@noaa.gov","gender":"Male","weight":48,"dob":"1994-11-22"},
{"first_name":"Waite","last_name":"Jordon","email":"wjordon4@auda.org.au","gender":"Male","weight":77,"dob":"2003-07-19"},
{"first_name":"Fax","last_name":"Guarnier","email":"fguarnier5@mit.edu","gender":"Male","weight":87,"dob":"1997-01-12"},
{"first_name":"Codie","last_name":"Lukesch","email":"clukesch6@weibo.com","gender":"Male","weight":74,"dob":"2004-01-24"},
{"first_name":"Nesta","last_name":"Caldwall","email":"ncaldwall7@apache.org","gender":"Female","weight":93,"dob":"1998-05-21"},
{"first_name":"Baudoin","last_name":"Bartoletti","email":"bbartoletti8@chron.com","gender":"Male","weight":79,"dob":"1998-10-05"},
{"first_name":"Ursulina","last_name":"Reasce","email":"ureasce9@cnbc.com","gender":"Female","weight":88,"dob":"1996-07-16"},
{"first_name":"Morgun","last_name":"Basilone","email":"mbasilonea@ucla.edu","gender":"Male","weight":61,"dob":"2000-03-04"},
{"first_name":"Phil","last_name":"Joseland","email":"pjoselandb@lulu.com","gender":"Male","weight":67,"dob":"2002-09-06"},
{"first_name":"Carlota","last_name":"Horwell","email":"chorwellc@jigsy.com","gender":"Female","weight":85,"dob":"1996-01-12"},
{"first_name":"Bradney","last_name":"Cheal","email":"bcheald@vinaora.com","gender":"Male","weight":67,"dob":"1997-11-11"},
{"first_name":"Marlow","last_name":"Babb","email":"mbabbe@comsenz.com","gender":"Male","weight":80,"dob":"1994-06-15"},
{"first_name":"Rosita","last_name":"Threlfall","email":"rthrelfallf@dagondesign.com","gender":"Female","weight":60,"dob":"1995-01-13"},
{"first_name":"Kerk","last_name":"Mayho","email":"kmayhog@multiply.com","gender":"Male","weight":64,"dob":"1997-04-12"},
{"first_name":"Freida","last_name":"Jime","email":"fjimeh@i2i.jp","gender":"Female","weight":89,"dob":"2004-09-08"},
{"first_name":"Chevy","last_name":"Dennett","email":"cdennetti@slideshare.net","gender":"Male","weight":94,"dob":"1995-11-06"},
{"first_name":"Phillipe","last_name":"Chesley","email":"pchesleyj@weebly.com","gender":"Male","weight":92,"dob":"2002-01-17"},
{"first_name":"Cointon","last_name":"Kivelhan","email":"ckivelhank@symantec.com","gender":"Male","weight":59,"dob":"1997-10-21"},
{"first_name":"Marlin","last_name":"Landreth","email":"mlandrethl@chron.com","gender":"Male","weight":57,"dob":"1996-01-04"},
{"first_name":"Cole","last_name":"Gurnay","email":"cgurnaym@si.edu","gender":"Male","weight":100,"dob":"2002-12-23"},
{"first_name":"Lorry","last_name":"Hunnaball","email":"lhunnaballn@google.cn","gender":"Female","weight":42,"dob":"1996-03-01"},
{"first_name":"Jabez","last_name":"Tressler","email":"jtresslero@merriam-webster.com","gender":"Male","weight":46,"dob":"2003-06-30"},
{"first_name":"Winona","last_name":"Gradwell","email":"wgradwellp@webmd.com","gender":"Female","weight":62,"dob":"1998-08-07"},
{"first_name":"Vivien","last_name":"Aldritt","email":"valdrittq@1688.com","gender":"Female","weight":58,"dob":"2003-05-02"},
{"first_name":"Umeko","last_name":"Crennan","email":"ucrennanr@prlog.org","gender":"Female","weight":99,"dob":"1999-07-18"},
{"first_name":"Klara","last_name":"Grenshiels","email":"kgrenshielss@feedburner.com","gender":"Female","weight":66,"dob":"1997-12-14"},
{"first_name":"Deane","last_name":"Drohun","email":"ddrohunt@sourceforge.net","gender":"Male","weight":82,"dob":"1998-03-17"},
{"first_name":"Agace","last_name":"Foulser","email":"afoulseru@squidoo.com","gender":"Female","weight":70,"dob":"1994-07-28"},
{"first_name":"Merrily","last_name":"Furst","email":"mfurstv@i2i.jp","gender":"Female","weight":88,"dob":"2004-01-07"},
{"first_name":"Del","last_name":"Cops","email":"dcopsw@hc360.com","gender":"Male","weight":92,"dob":"1998-09-13"},
{"first_name":"Hayward","last_name":"Pickering","email":"hpickeringx@blogtalkradio.com","gender":"Male","weight":56,"dob":"1999-12-07"},
{"first_name":"Celine","last_name":"Jimeno","email":"cjimenoy@de.vu","gender":"Female","weight":52,"dob":"2000-04-13"},
{"first_name":"Bea","last_name":"Lyburn","email":"blyburnz@free.fr","gender":"Female","weight":49,"dob":"2004-12-06"},
{"first_name":"Sonja","last_name":"Ambroziak","email":"sambroziak10@ebay.co.uk","gender":"Female","weight":89,"dob":"1998-01-03"},
{"first_name":"Mano","last_name":"Swinburne","email":"mswinburne11@dyndns.org","gender":"Male","weight":102,"dob":"2000-09-06"},
{"first_name":"Rhys","last_name":"Tsar","email":"rtsar12@skyrock.com","gender":"Male","weight":46,"dob":"2001-03-28"},
{"first_name":"Esmaria","last_name":"Pawle","email":"epawle13@desdev.cn","gender":"Female","weight":60,"dob":"1997-09-12"},
{"first_name":"Katee","last_name":"Radeliffe","email":"kradeliffe14@addtoany.com","gender":"Female","weight":70,"dob":"1997-08-15"},
{"first_name":"Demetrius","last_name":"Coutthart","email":"dcoutthart15@hud.gov","gender":"Male","weight":88,"dob":"2000-09-27"},
{"first_name":"Harri","last_name":"Fomichyov","email":"hfomichyov16@liveinternet.ru","gender":"Female","weight":47,"dob":"1996-08-20"},
{"first_name":"Leanor","last_name":"Brumbie","email":"lbrumbie17@zimbio.com","gender":"Female","weight":68,"dob":"1997-12-01"},
{"first_name":"Lyon","last_name":"Baldini","email":"lbaldini18@smugmug.com","gender":"Male","weight":66,"dob":"2003-02-16"},
{"first_name":"Mitch","last_name":"Tropman","email":"mtropman19@com.com","gender":"Male","weight":88,"dob":"2000-09-06"},
{"first_name":"Graig","last_name":"Tasker","email":"gtasker1a@vimeo.com","gender":"Male","weight":50,"dob":"1994-04-03"},
{"first_name":"Selestina","last_name":"Meininking","email":"smeininking1b@tamu.edu","gender":"Female","weight":101,"dob":"1999-11-09"},
{"first_name":"Delmer","last_name":"Castagnier","email":"dcastagnier1c@ebay.com","gender":"Male","weight":71,"dob":"1997-10-12"},
{"first_name":"Dael","last_name":"De Gregario","email":"ddegregario1d@google.ca","gender":"Male","weight":45,"dob":"2000-07-13"},
{"first_name":"Tremaine","last_name":"Herkess","email":"therkess1e@wikimedia.org","gender":"Male","weight":53,"dob":"2001-03-23"},
{"first_name":"Meryl","last_name":"Millen","email":"mmillen1f@jalbum.net","gender":"Male","weight":97,"dob":"2003-07-26"},
{"first_name":"Laina","last_name":"Tubble","email":"ltubble1g@nymag.com","gender":"Female","weight":96,"dob":"2003-10-29"},
{"first_name":"Sam","last_name":"Itzhaki","email":"sitzhaki1h@hibu.com","gender":"Male","weight":59,"dob":"2000-12-28"},
{"first_name":"Wolfgang","last_name":"Rihanek","email":"wrihanek1i@nbcnews.com","gender":"Male","weight":77,"dob":"1997-04-02"},
{"first_name":"Skell","last_name":"Pirrey","email":"spirrey1j@e-recht24.de","gender":"Male","weight":85,"dob":"2001-03-11"},
{"first_name":"Lin","last_name":"Cumpton","email":"lcumpton1k@zdnet.com","gender":"Female","weight":52,"dob":"2000-02-06"},
{"first_name":"Ignace","last_name":"Andrioni","email":"iandrioni1l@multiply.com","gender":"Male","weight":80,"dob":"1995-04-18"},
{"first_name":"Lorettalorna","last_name":"Croci","email":"lcroci1m@furl.net","gender":"Female","weight":80,"dob":"1995-08-12"},
{"first_name":"Vinny","last_name":"Hawkins","email":"vhawkins1n@bigcartel.com","gender":"Male","weight":47,"dob":"2000-06-19"},
{"first_name":"Skylar","last_name":"Stallwood","email":"sstallwood1o@aboutads.info","gender":"Male","weight":85,"dob":"2005-07-06"},
{"first_name":"Darsey","last_name":"Blackie","email":"dblackie1p@a8.net","gender":"Female","weight":57,"dob":"1998-03-04"},
{"first_name":"Jaye","last_name":"Mirams","email":"jmirams1q@amazon.com","gender":"Male","weight":42,"dob":"2004-09-10"},
{"first_name":"Chauncey","last_name":"Wolters","email":"cwolters1r@networksolutions.com","gender":"Male","weight":68,"dob":"1998-03-16"},
{"first_name":"Monah","last_name":"MacKibbon","email":"mmackibbon1s@twitpic.com","gender":"Female","weight":94,"dob":"1994-08-15"},
{"first_name":"Mill","last_name":"Tapply","email":"mtapply1t@edublogs.org","gender":"Male","weight":67,"dob":"1994-11-27"},
{"first_name":"Humphrey","last_name":"Scotchford","email":"hscotchford1u@163.com","gender":"Male","weight":43,"dob":"2001-12-24"},
{"first_name":"Claudia","last_name":"Presshaugh","email":"cpresshaugh1v@nature.com","gender":"Female","weight":69,"dob":"1997-06-30"},
{"first_name":"Stanley","last_name":"Laviss","email":"slaviss1w@usnews.com","gender":"Male","weight":74,"dob":"1998-04-17"},
{"first_name":"Nickolai","last_name":"Lavalle","email":"nlavalle1x@cpanel.net","gender":"Male","weight":46,"dob":"2000-10-18"},
{"first_name":"Elston","last_name":"Schreurs","email":"eschreurs1y@uiuc.edu","gender":"Male","weight":71,"dob":"1998-06-01"},
{"first_name":"Ax","last_name":"Surpliss","email":"asurpliss1z@dot.gov","gender":"Male","weight":70,"dob":"1996-09-27"},
{"first_name":"Alexi","last_name":"Josovitz","email":"ajosovitz20@newsvine.com","gender":"Female","weight":94,"dob":"2001-12-23"},
{"first_name":"Marcy","last_name":"Bickerstaff","email":"mbickerstaff21@uol.com.br","gender":"Female","weight":66,"dob":"2004-05-06"},
{"first_name":"Yorgo","last_name":"Heam","email":"yheam22@ning.com","gender":"Male","weight":67,"dob":"2000-09-21"},
{"first_name":"Chaunce","last_name":"Girtin","email":"cgirtin23@amazon.co.jp","gender":"Male","weight":96,"dob":"2004-11-13"},
{"first_name":"Rodina","last_name":"Kail","email":"rkail24@blogs.com","gender":"Female","weight":65,"dob":"2005-01-19"},
{"first_name":"Aldridge","last_name":"Amori","email":"aamori25@reverbnation.com","gender":"Male","weight":73,"dob":"1998-11-27"},
{"first_name":"Kaile","last_name":"Tyrone","email":"ktyrone26@simplemachines.org","gender":"Female","weight":71,"dob":"2000-03-10"},
{"first_name":"Deanne","last_name":"Grayshan","email":"dgrayshan27@bravesites.com","gender":"Female","weight":61,"dob":"1995-03-21"},
{"first_name":"Archambault","last_name":"Aliman","email":"aaliman28@latimes.com","gender":"Male","weight":81,"dob":"2000-04-04"},
{"first_name":"Fara","last_name":"Diego","email":"fdiego29@japanpost.jp","gender":"Female","weight":90,"dob":"1999-08-16"},
{"first_name":"Turner","last_name":"Harradence","email":"tharradence2a@posterous.com","gender":"Male","weight":96,"dob":"2002-05-05"},
{"first_name":"Pascale","last_name":"De Lasci","email":"pdelasci2b@bing.com","gender":"Male","weight":66,"dob":"1995-03-24"},
{"first_name":"Joscelin","last_name":"Batsford","email":"jbatsford2c@microsoft.com","gender":"Female","weight":65,"dob":"1999-12-14"},
{"first_name":"Robby","last_name":"Petrushanko","email":"rpetrushanko2d@va.gov","gender":"Female","weight":79,"dob":"2003-04-22"},
{"first_name":"Kellen","last_name":"Twinterman","email":"ktwinterman2e@aol.com","gender":"Male","weight":80,"dob":"2000-09-29"},
{"first_name":"Gena","last_name":"McCaughren","email":"gmccaughren2f@1und1.de","gender":"Female","weight":92,"dob":"1995-01-12"},
{"first_name":"Pincus","last_name":"Custy","email":"pcusty2g@google.com.br","gender":"Male","weight":59,"dob":"2004-10-29"},
{"first_name":"Odelinda","last_name":"Cluely","email":"ocluely2h@mashable.com","gender":"Female","weight":42,"dob":"2001-01-04"},
{"first_name":"Bartholomeo","last_name":"Chesshire","email":"bchesshire2i@squidoo.com","gender":"Male","weight":42,"dob":"1999-05-24"},
{"first_name":"Lawrence","last_name":"Calvard","email":"lcalvard2j@boston.com","gender":"Male","weight":53,"dob":"1996-03-07"},
{"first_name":"Shanon","last_name":"Sharratt","email":"ssharratt2k@whitehouse.gov","gender":"Female","weight":64,"dob":"1999-03-04"},
{"first_name":"Meta","last_name":"Gabbitis","email":"mgabbitis2l@wired.com","gender":"Female","weight":40,"dob":"2005-09-04"},
{"first_name":"Alan","last_name":"Hoyes","email":"ahoyes2m@umich.edu","gender":"Male","weight":54,"dob":"1994-12-14"},
{"first_name":"Eziechiele","last_name":"Cumpsty","email":"ecumpsty2n@acquirethisname.com","gender":"Male","weight":91,"dob":"1996-12-23"},
{"first_name":"Ezra","last_name":"Hunting","email":"ehunting2o@house.gov","gender":"Male","weight":45,"dob":"1997-02-10"},
{"first_name":"Charil","last_name":"Besque","email":"cbesque2p@instagram.com","gender":"Female","weight":73,"dob":"2004-04-16"},
{"first_name":"Abram","last_name":"Viscovi","email":"aviscovi2q@europa.eu","gender":"Male","weight":76,"dob":"2004-04-20"},
{"first_name":"Roobbie","last_name":"Hance","email":"rhance2r@craigslist.org","gender":"Female","weight":41,"dob":"2000-09-14"}]
        for c in customers:
            customer = Customer(**c)
            customer.save()
        self.stdout.write(
            self.style.SUCCESS('Successfully populated the database')
        )

# python manage.py populatedb